// Static sample data for announcements, members, and gallery used while Firebase is not yet wired up.
import type { Announcement } from "@/types/announcement";
import type { Member } from "@/types/member";
import type { GalleryPhoto } from "@/types/gallery";

function daysAgo(days: number, hours = 0): Date {
  const d = new Date();
  d.setDate(d.getDate() - days);
  d.setHours(d.getHours() - hours);
  return d;
}

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: "1",
    title: "Spring Rush Week Kickoff",
    body: "Rush week starts this Monday! We have an exciting lineup of events planned — info sessions, a case workshop, and a social night. Invite anyone you think would be a great fit. Check the full schedule in our Slack.",
    authorId: "user-sarah",
    authorName: "Sarah Kim",
    authorAvatar: "https://i.pravatar.cc/150?u=sarah",
    imageUrls: ["https://picsum.photos/seed/rush-week/800/400"],
    createdAt: daysAgo(0, 2),
    likedBy: [],
    commentCount: 0,
  },
  {
    id: "2",
    title: "Chapter Meeting — Wednesday 6 PM",
    body: "Reminder: chapter meeting this Wednesday at 6 PM in Paccar 291. We'll be going over committee updates and voting on the spring fundraiser proposal. Attendance is mandatory for actives.",
    authorId: "user-james",
    authorName: "James Tanaka",
    authorAvatar: "https://i.pravatar.cc/150?u=james",
    imageUrls: [],
    createdAt: daysAgo(1, 5),
    likedBy: [],
    commentCount: 0,
  },
  {
    id: "3",
    title: "Professional Development: Resume Workshop Recap",
    body: "Thanks to everyone who came out to the resume workshop last Friday! The slides and templates have been uploaded to the shared drive. If you missed it, reach out to your PD committee rep for a 1-on-1 review session.",
    authorId: "dev-user",
    authorName: "Dev User",
    imageUrls: ["https://picsum.photos/seed/resume-workshop/800/400"],
    createdAt: daysAgo(3),
    likedBy: [],
    commentCount: 0,
  },
  {
    id: "4",
    title: "Fundraiser Update: Bake Sale Results",
    body: "The bake sale raised $847 — our best one yet! Huge shoutout to the fundraising committee and everyone who baked or volunteered. The funds will go toward our spring formal.",
    authorId: "user-priya",
    authorName: "Priya Patel",
    authorAvatar: "https://i.pravatar.cc/150?u=priya",
    imageUrls: [
      "https://picsum.photos/seed/bake-sale/800/400",
      "https://picsum.photos/seed/bake-sale-2/800/400",
    ],
    createdAt: daysAgo(5, 3),
    likedBy: [],
    commentCount: 0,
  },
  {
    id: "5",
    title: "Social Night This Saturday",
    body: "Join us this Saturday at 8 PM for game night at the chapter house. We'll have board games, snacks, and a Mario Kart tournament. Feel free to bring a friend!",
    authorId: "user-sarah",
    authorName: "Sarah Kim",
    authorAvatar: "https://i.pravatar.cc/150?u=sarah",
    imageUrls: [],
    createdAt: daysAgo(7),
    likedBy: [],
    commentCount: 0,
  },
  {
    id: "6",
    title: "Welcome New Pledge Class — Epsilon!",
    body: "We're thrilled to welcome 12 new pledges to the Epsilon pledge class. Get ready for an incredible quarter of growth, brotherhood, and professional development. Current actives — please introduce yourselves at the next meeting!",
    authorId: "user-james",
    authorName: "James Tanaka",
    authorAvatar: "https://i.pravatar.cc/150?u=james",
    imageUrls: ["https://picsum.photos/seed/pledge-class/800/400"],
    createdAt: daysAgo(12),
    likedBy: [],
    commentCount: 0,
  },
];

// Family lines:
// fam-1: ghost "Alex Thompson" → Sarah → Priya → Emily → Ryan → Sofia
// fam-2: James (root) → Marcus → David
// fam-3: Hannah (root, alumni) → Jordan → Aisha → Kevin
export const MOCK_MEMBERS: Member[] = [
  {
    uid: "user-sarah",
    firstName: "Sarah",
    lastName: "Kim",
    preferredName: null,
    profilePhotoUrl: "https://i.pravatar.cc/150?u=sarah-kim",
    pledgeClassQuarter: "Fall",
    pledgeClassYear: 2023,
    status: "active",
    role: "President",
    familyId: "fam-1",
    familyName: null,
    bigUid: null,
    bigName: "Alex Thompson",
    major: "Computer Science",
    graduationYear: 2026,
    email: "skim@uw.edu",
    phone: "(206) 555-0101",
    preferredContact: "email",
    socialLinks: [
      { platform: "LinkedIn", url: "https://linkedin.com/in/sarahkim" },
      { platform: "GitHub", url: "https://github.com/sarahkim" },
    ],
    bio: "CS major passionate about product management and fintech. Leading the chapter through our biggest year yet.",
    industries: ["Technology", "Finance"],
    joinedAt: new Date("2023-09-15"),
    lastActive: new Date(),
    isAdmin: true,
  },
  {
    uid: "user-james",
    firstName: "James",
    lastName: "Tanaka",
    preferredName: null,
    profilePhotoUrl: "https://i.pravatar.cc/150?u=james-tanaka",
    pledgeClassQuarter: "Fall",
    pledgeClassYear: 2023,
    status: "active",
    role: "VP of Finance",
    familyId: "fam-2",
    familyName: null,
    bigUid: null,
    bigName: "Alex Thompson",
    major: "Finance",
    graduationYear: 2026,
    email: "jtanaka@uw.edu",
    phone: "(206) 555-0102",
    preferredContact: "phone",
    socialLinks: [
      { platform: "LinkedIn", url: "https://linkedin.com/in/jamestanaka" },
    ],
    bio: "Interested in investment banking and equity research. Running our chapter finances and fundraising.",
    industries: ["Finance", "Consulting"],
    joinedAt: new Date("2023-09-15"),
    lastActive: new Date(),
    isAdmin: true,
  },
  {
    uid: "user-hannah",
    firstName: "Hannah",
    lastName: "Lee",
    preferredName: null,
    profilePhotoUrl: "https://i.pravatar.cc/150?u=hannah-lee",
    pledgeClassQuarter: "Fall",
    pledgeClassYear: 2023,
    status: "alumni",
    role: null,
    familyId: "fam-3",
    familyName: null,
    bigUid: null,
    bigName: null,
    major: "Supply Chain Management",
    graduationYear: 2025,
    email: "hlee@uw.edu",
    phone: null,
    preferredContact: "email",
    socialLinks: [
      { platform: "LinkedIn", url: "https://linkedin.com/in/hannahlee" },
    ],
    bio: "Working in supply chain ops at Boeing. Proud Alpha class alum!",
    industries: ["Supply Chain", "Manufacturing"],
    joinedAt: new Date("2023-09-15"),
    lastActive: new Date("2025-05-20"),
    isAdmin: false,
  },
  {
    uid: "user-priya",
    firstName: "Priya",
    lastName: "Patel",
    preferredName: null,
    profilePhotoUrl: "https://i.pravatar.cc/150?u=priya-patel",
    pledgeClassQuarter: "Spring",
    pledgeClassYear: 2024,
    status: "alumni",
    role: null,
    familyId: "fam-1",
    familyName: null,
    bigUid: "user-sarah",
    bigName: null,
    major: "Information Systems",
    graduationYear: 2025,
    email: "ppatel@uw.edu",
    phone: null,
    preferredContact: "email",
    socialLinks: [
      { platform: "LinkedIn", url: "https://linkedin.com/in/priyapatel" },
    ],
    bio: "Now working as a business analyst at Amazon. Always happy to help current members with career advice!",
    industries: ["Technology", "Consulting"],
    joinedAt: new Date("2023-01-10"),
    lastActive: new Date("2025-06-01"),
    isAdmin: false,
  },
  {
    uid: "user-marcus",
    firstName: "Marcus",
    lastName: "Chen",
    preferredName: "Marc",
    profilePhotoUrl: "https://i.pravatar.cc/150?u=marcus-chen",
    pledgeClassQuarter: "Spring",
    pledgeClassYear: 2024,
    status: "active",
    role: null,
    familyId: "fam-2",
    familyName: null,
    bigUid: "user-james",
    bigName: null,
    major: "Business Administration",
    graduationYear: 2027,
    email: "mchen@uw.edu",
    phone: "(206) 555-0104",
    preferredContact: null,
    socialLinks: [],
    bio: null,
    industries: ["Marketing", "Entrepreneurship"],
    joinedAt: new Date("2024-01-12"),
    lastActive: new Date(),
    isAdmin: false,
  },
  {
    uid: "user-emily",
    firstName: "Emily",
    lastName: "Nguyen",
    preferredName: "Em",
    profilePhotoUrl: "https://i.pravatar.cc/150?u=emily-nguyen",
    pledgeClassQuarter: "Fall",
    pledgeClassYear: 2024,
    status: "active",
    role: "VP of Marketing",
    familyId: "fam-1",
    familyName: null,
    bigUid: "user-priya",
    bigName: null,
    major: "Marketing",
    graduationYear: 2027,
    email: "enguyen@uw.edu",
    phone: "(206) 555-0105",
    preferredContact: "phone",
    socialLinks: [
      { platform: "LinkedIn", url: "https://linkedin.com/in/emilynguyen" },
      { platform: "Instagram", url: "https://instagram.com/em.nguyen" },
    ],
    bio: "Marketing nerd who loves brand strategy and social media. Running all chapter communications and outreach.",
    industries: ["Marketing", "Media"],
    joinedAt: new Date("2024-09-20"),
    lastActive: new Date(),
    isAdmin: false,
  },
  {
    uid: "user-david",
    firstName: "David",
    lastName: "Park",
    preferredName: null,
    profilePhotoUrl: "https://i.pravatar.cc/150?u=david-park",
    pledgeClassQuarter: "Fall",
    pledgeClassYear: 2024,
    status: "active",
    role: null,
    familyId: "fam-2",
    familyName: null,
    bigUid: "user-marcus",
    bigName: null,
    major: "Economics",
    graduationYear: 2026,
    email: "dpark@uw.edu",
    phone: null,
    preferredContact: "email",
    socialLinks: [],
    bio: null,
    industries: ["Finance", "Real Estate"],
    joinedAt: new Date("2024-09-20"),
    lastActive: new Date(),
    isAdmin: false,
  },
  {
    uid: "user-jordan",
    firstName: "Jordan",
    lastName: "Williams",
    preferredName: "JW",
    profilePhotoUrl: "https://i.pravatar.cc/150?u=jordan-williams",
    pledgeClassQuarter: "Fall",
    pledgeClassYear: 2024,
    status: "active",
    role: "Secretary",
    familyId: "fam-3",
    familyName: null,
    bigUid: "user-hannah",
    bigName: null,
    major: "Computer Science",
    graduationYear: 2026,
    email: "jwilliams@uw.edu",
    phone: "(206) 555-0112",
    preferredContact: "email",
    socialLinks: [
      { platform: "LinkedIn", url: "https://linkedin.com/in/jordanwilliams" },
      { platform: "GitHub", url: "https://github.com/jwilliams" },
    ],
    bio: "Full-stack dev who loves hackathons. Keeping the chapter organized one meeting at a time.",
    industries: ["Technology", "Entrepreneurship"],
    joinedAt: new Date("2024-09-20"),
    lastActive: new Date(),
    isAdmin: false,
  },
  {
    uid: "user-ryan",
    firstName: "Ryan",
    lastName: "O'Brien",
    preferredName: null,
    profilePhotoUrl: "https://i.pravatar.cc/150?u=ryan-obrien",
    pledgeClassQuarter: "Spring",
    pledgeClassYear: 2025,
    status: "active",
    role: "Treasurer",
    familyId: "fam-2",
    familyName: null,
    bigUid: "user-marcus",
    bigName: null,
    major: "Accounting",
    graduationYear: 2027,
    email: "robrien@uw.edu",
    phone: "(206) 555-0108",
    preferredContact: "phone",
    socialLinks: [
      { platform: "LinkedIn", url: "https://linkedin.com/in/ryanobrien" },
    ],
    bio: null,
    industries: ["Finance", "Accounting"],
    joinedAt: new Date("2025-01-08"),
    lastActive: new Date(),
    isAdmin: false,
  },
  {
    uid: "user-aisha",
    firstName: "Aisha",
    lastName: "Johnson",
    preferredName: null,
    profilePhotoUrl: "https://i.pravatar.cc/150?u=aisha-johnson",
    pledgeClassQuarter: "Spring",
    pledgeClassYear: 2025,
    status: "active",
    role: null,
    familyId: "fam-3",
    familyName: null,
    bigUid: "user-jordan",
    bigName: null,
    major: "Computer Science",
    graduationYear: 2028,
    email: "ajohnson@uw.edu",
    phone: "(206) 555-0107",
    preferredContact: null,
    socialLinks: [
      { platform: "GitHub", url: "https://github.com/aishaj" },
    ],
    bio: "Freshman CS major excited about AI/ML and startups.",
    industries: ["Technology"],
    joinedAt: new Date("2025-01-08"),
    lastActive: new Date(),
    isAdmin: false,
  },
  {
    uid: "user-sofia",
    firstName: "Sofia",
    lastName: "Martinez",
    preferredName: null,
    profilePhotoUrl: "https://i.pravatar.cc/150?u=sofia-martinez",
    pledgeClassQuarter: "Fall",
    pledgeClassYear: 2025,
    status: "active",
    role: null,
    familyId: "fam-3",
    familyName: null,
    bigUid: "user-jordan",
    bigName: null,
    major: "Finance",
    graduationYear: 2028,
    email: "smartinez@uw.edu",
    phone: null,
    preferredContact: "email",
    socialLinks: [],
    bio: "New pledge excited to learn from the chapter!",
    industries: ["Finance"],
    joinedAt: new Date("2025-09-15"),
    lastActive: new Date(),
    isAdmin: false,
  },
  {
    uid: "user-kevin",
    firstName: "Kevin",
    lastName: "Tran",
    preferredName: null,
    profilePhotoUrl: "https://i.pravatar.cc/150?u=kevin-tran",
    pledgeClassQuarter: "Fall",
    pledgeClassYear: 2025,
    status: "active",
    role: null,
    familyId: "fam-3",
    familyName: null,
    bigUid: "user-aisha",
    bigName: null,
    major: "Information Systems",
    graduationYear: 2028,
    email: "ktran@uw.edu",
    phone: "(206) 555-0110",
    preferredContact: null,
    socialLinks: [
      { platform: "LinkedIn", url: "https://linkedin.com/in/kevintran" },
    ],
    bio: null,
    industries: ["Technology", "Consulting"],
    joinedAt: new Date("2025-09-15"),
    lastActive: new Date(),
    isAdmin: false,
  },
];

export const MOCK_GALLERY: GalleryPhoto[] = [
  {
    id: "g1",
    imageUrl: "https://picsum.photos/seed/akpsi-formal/800/600",
    caption: "Spring Formal 2025",
    uploadedBy: "Sarah Kim",
    uploadedAt: daysAgo(0, 3),
    aspectRatio: 800 / 600,
  },
  {
    id: "g2",
    imageUrl: "https://picsum.photos/seed/akpsi-pledge/800/1050",
    caption: "Epsilon pledge class welcome night",
    uploadedBy: "Emily Nguyen",
    uploadedAt: daysAgo(1),
    aspectRatio: 800 / 1050,
  },
  {
    id: "g3",
    imageUrl: "https://picsum.photos/seed/akpsi-workshop/800/500",
    caption: "Resume workshop",
    uploadedBy: "James Tanaka",
    uploadedAt: daysAgo(2),
    aspectRatio: 800 / 500,
  },
  {
    id: "g4",
    imageUrl: "https://picsum.photos/seed/akpsi-bake/800/900",
    caption: "Bake sale fundraiser",
    uploadedBy: "Priya Patel",
    uploadedAt: daysAgo(3),
    aspectRatio: 800 / 900,
  },
  {
    id: "g5",
    imageUrl: "https://picsum.photos/seed/akpsi-social/800/550",
    uploadedBy: "Marcus Chen",
    uploadedAt: daysAgo(4),
    aspectRatio: 800 / 550,
  },
  {
    id: "g6",
    imageUrl: "https://picsum.photos/seed/akpsi-rush/800/1100",
    caption: "Rush week info night",
    uploadedBy: "Sarah Kim",
    uploadedAt: daysAgo(5),
    aspectRatio: 800 / 1100,
  },
  {
    id: "g7",
    imageUrl: "https://picsum.photos/seed/akpsi-game/800/620",
    caption: "Game night at the chapter house",
    uploadedBy: "Jordan Williams",
    uploadedAt: daysAgo(7),
    aspectRatio: 800 / 620,
  },
  {
    id: "g8",
    imageUrl: "https://picsum.photos/seed/akpsi-meeting/800/480",
    uploadedBy: "Ryan O'Brien",
    uploadedAt: daysAgo(9),
    aspectRatio: 800 / 480,
  },
  {
    id: "g9",
    imageUrl: "https://picsum.photos/seed/akpsi-retreat/800/950",
    caption: "Winter leadership retreat",
    uploadedBy: "Emily Nguyen",
    uploadedAt: daysAgo(11),
    aspectRatio: 800 / 950,
  },
  {
    id: "g10",
    imageUrl: "https://picsum.photos/seed/akpsi-panel/800/560",
    caption: "Alumni career panel",
    uploadedBy: "James Tanaka",
    uploadedAt: daysAgo(14),
    aspectRatio: 800 / 560,
  },
  {
    id: "g11",
    imageUrl: "https://picsum.photos/seed/akpsi-study/800/700",
    uploadedBy: "Aisha Johnson",
    uploadedAt: daysAgo(16),
    aspectRatio: 800 / 700,
  },
  {
    id: "g12",
    imageUrl: "https://picsum.photos/seed/akpsi-charity/800/1000",
    caption: "Charity walk for the community",
    uploadedBy: "David Park",
    uploadedAt: daysAgo(20),
    aspectRatio: 800 / 1000,
  },
];
